export const FOOD_CALORIES_MAP = {
  apple_pie: 320,
  baby_back_ribs: 430,
  baklava: 290,
  beef_carpaccio: 180,
  beef_tartare: 250,
  beet_salad: 160,
  beignets: 290,
  bibimbap: 550,
  bread_pudding: 310,
  breakfast_burrito: 500,
  bruschetta: 170,
  caesar_salad: 330,
  cannoli: 260,
  caprese_salad: 220,
  carrot_cake: 360,
  ceviche: 180,
  cheese_plate: 420,
  cheesecake: 400,
  chicken_curry: 420,
  chicken_quesadilla: 450,
  chicken_wings: 430,
  chocolate_cake: 390,
  chocolate_mousse: 320,
  churros: 280,
  clam_chowder: 230,
  club_sandwich: 480,
  crab_cakes: 300,
  creme_brulee: 300,
  croque_madame: 520,
  cup_cakes: 240,
  deviled_eggs: 180,
  donuts: 260,
  dumplings: 300,
  edamame: 140,
  eggs_benedict: 460,
  escargots: 180,
  falafel: 330,
  filet_mignon: 430,
  fish_and_chips: 600,
  foie_gras: 370,
  french_fries: 365,
  french_onion_soup: 250,
  french_toast: 350,
  fried_calamari: 320,
  fried_rice: 420,
  frozen_yogurt: 180,
  garlic_bread: 210,
  gnocchi: 370,
  greek_salad: 220,
  grilled_cheese_sandwich: 400,
  grilled_salmon: 360,
  guacamole: 180,
  gyoza: 280,
  hamburger: 520,
  hot_and_sour_soup: 150,
  hot_dog: 290,
  huevos_rancheros: 400,
  hummus: 180,
  ice_cream: 210,
  lasagna: 450,
  lobster_bisque: 240,
  lobster_roll_sandwich: 430,
  macaroni_and_cheese: 420,
  macarons: 230,
  miso_soup: 80,
  mussels: 220,
  nachos: 500,
  omelette: 240,
  onion_rings: 340,
  oysters: 110,
  pad_thai: 520,
  paella: 480,
  pancakes: 350,
  panna_cotta: 260,
  peking_duck: 470,
  pho: 380,
  pizza: 420,
  pork_chop: 390,
  poutine: 520,
  prime_rib: 500,
  pulled_pork_sandwich: 480,
  ramen: 450,
  ravioli: 360,
  red_velvet_cake: 390,
  risotto: 410,
  samosa: 260,
  sashimi: 140,
  scallops: 190,
  seaweed_salad: 90,
  shrimp_and_grits: 430,
  spaghetti_bolognese: 430,
  spaghetti_carbonara: 500,
  spring_rolls: 190,
  steak: 450,
  strawberry_shortcake: 300,
  sushi: 300,
  tacos: 320,
  takoyaki: 300,
  tiramisu: 330,
  tuna_tartare: 180,
  waffles: 370
};
export const FOOD_NAME_MAP = {
  apple_pie: "Apple Pie",
  baby_back_ribs: "Baby Back Ribs",
  baklava: "Baklava",
  beef_carpaccio: "Beef Carpaccio",
  beef_tartare: "Beef Tartare",
  beet_salad: "Beet Salad",
  beignets: "Beignets",
  bibimbap: "Bibimbap",
  bread_pudding: "Bread Pudding",
  breakfast_burrito: "Breakfast Burrito",
  bruschetta: "Bruschetta",
  caesar_salad: "Caesar Salad",
  cannoli: "Cannoli",
  caprese_salad: "Caprese Salad",
  carrot_cake: "Carrot Cake",
  ceviche: "Ceviche",
  cheese_plate: "Cheese Plate",
  cheesecake: "Cheesecake",
  chicken_curry: "Chicken Curry",
  chicken_quesadilla: "Chicken Quesadilla",
  chicken_wings: "Chicken Wings",
  chocolate_cake: "Chocolate Cake",
  chocolate_mousse: "Chocolate Mousse",
  churros: "Churros",
  clam_chowder: "Clam Chowder",
  club_sandwich: "Club Sandwich",
  crab_cakes: "Crab Cakes",
  creme_brulee: "Creme Brulee",
  croque_madame: "Croque Madame",
  cup_cakes: "Cup Cakes",
  deviled_eggs: "Deviled Eggs",
  donuts: "Donuts",
  dumplings: "Dumplings",
  edamame: "Edamame",
  eggs_benedict: "Eggs Benedict",
  escargots: "Escargots",
  falafel: "Falafel",
  filet_mignon: "Filet Mignon",
  fish_and_chips: "Fish and Chips",
  foie_gras: "Foie Gras",
  french_fries: "French Fries",
  french_onion_soup: "French Onion Soup",
  french_toast: "French Toast",
  fried_calamari: "Fried Calamari",
  fried_rice: "Fried Rice",
  frozen_yogurt: "Frozen Yogurt",
  garlic_bread: "Garlic Bread",
  gnocchi: "Gnocchi",
  greek_salad: "Greek Salad",
  grilled_cheese_sandwich: "Grilled Cheese Sandwich",
  grilled_salmon: "Grilled Salmon",
  guacamole: "Guacamole",
  gyoza: "Gyoza",
  hamburger: "Hamburger",
  hot_and_sour_soup: "Hot and Sour Soup",
  hot_dog: "Hot Dog",
  huevos_rancheros: "Huevos Rancheros",
  hummus: "Hummus",
  ice_cream: "Ice Cream",
  lasagna: "Lasagna",
  lobster_bisque: "Lobster Bisque",
  lobster_roll_sandwich: "Lobster Roll Sandwich",
  macaroni_and_cheese: "Macaroni and Cheese",
  macarons: "Macarons",
  miso_soup: "Miso Soup",
  mussels: "Mussels",
  nachos: "Nachos",
  omelette: "Omelette",
  onion_rings: "Onion Rings",
  oysters: "Oysters",
  pad_thai: "Pad Thai",
  paella: "Paella",
  pancakes: "Pancakes",
  panna_cotta: "Panna Cotta",
  peking_duck: "Peking Duck",
  pho: "Phở",
  pizza: "Pizza",
  pork_chop: "Pork Chop",
  poutine: "Poutine",
  prime_rib: "Prime Rib",
  pulled_pork_sandwich: "Pulled Pork Sandwich",
  ramen: "Ramen",
  ravioli: "Ravioli",
  red_velvet_cake: "Red Velvet Cake",
  risotto: "Risotto",
  samosa: "Samosa",
  sashimi: "Sashimi",
  scallops: "Scallops",
  seaweed_salad: "Seaweed Salad",
  shrimp_and_grits: "Shrimp and Grits",
  spaghetti_bolognese: "Spaghetti Bolognese",
  spaghetti_carbonara: "Spaghetti Carbonara",
  spring_rolls: "Spring Rolls",
  steak: "Steak",
  strawberry_shortcake: "Strawberry Shortcake",
  sushi: "Sushi",
  tacos: "Tacos",
  takoyaki: "Takoyaki",
  tiramisu: "Tiramisu",
  tuna_tartare: "Tuna Tartare",
  waffles: "Waffles"
};

export const getDefaultCaloriesByLabel = (label) => {
  if (!label) return 0;
  return FOOD_CALORIES_MAP[label] || 0;
};

export const getDisplayFoodName = (label) => {
  if (!label) return "";
  return FOOD_NAME_MAP[label] || label.replaceAll("_", " ");
};